# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=128)),
                ('lName', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
    ]
