# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20171031_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=128)),
                ('lName', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128, unique=True)),
            ],
        ),
    ]
